name:

on: 
  push:
    branches:
  pull_request:
    branches:
    
jobs:
  bash-hello:
    name: Run Bash Hello World
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
       
      - name: Make script executable
        run: chmod +x scripts/hello.sh
        
      - name: Run hello.sh
        run: ./scripts/hello.sh
        
  terraform-check:
    name: Terraform Init / Validate / Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform #todos los comandos se ejecutan dentro de terraform/
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Terraform
        uses: hashicorp/setip-terraform@v3
        with:
          terraform_version: 1.9.9
          
      - name: Terraform init
        run: terraform init
        
      - name: Terraform validate
        run: terraform validate
        
      - name: Terraform plan
        run: terraform plan -no-color